linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    require_trailing_commas: true
    always_use_package_imports: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
